### ISSUE TITLE
Hmmm Domains

### ISSUE THREAD

**Issue by PyWhy-3275** [fruithost/Modules#28] opened 2023-12-18 08:27 UTC
`[Mon Dec 18 13:16:49.673992 2023] [php:warn] [pid 71634] [client 68.69.186.30:34294] PHP Warning: Undefined array key "HTTP_HOST" in /etc/fruithost/panel/classes/Templating/Template.class.php on line 242
`

**Comment by Bizarrus** [comment] 2023-12-18 14:57
Please tell me the URL you are calling.

**Comment by PyWhy-3275** [comment] 2023-12-18 19:30
In what way?

**Comment by PyWhy-3275** [comment] 2023-12-18 19:31
This is when creating domains

**Comment by Bizarrus** [comment] 2023-12-18 22:06
I can't reproduce it, please specific your Bug.
I need a detailed information about that.

**Comment by PyWhy-3275** [comment] 2023-12-19 07:28
I'm just creating a domain and it doesn't create a folder for me with where the files should be + config for the domain in apache2

**Comment by PyWhy-3275** [comment] 2023-12-19 07:29
I can suggest that you go to Discard so that I can show you how it happens

**Comment by PyWhy-3275** [comment] 2023-12-19 07:29
![image](https://github.com/fruithost/Modules/assets/24767863/dd3ddbbf-e082-4274-ab4a-01f6add46ecd)

**Comment by Bizarrus** [comment] 2023-12-19 16:49
We do not currently offer personal premium support.

I therefore ask you to create a reasonable error description and a proper context when using the issues so that the problems can be traced and resolved.

Your issues are unspecific as well as information-absent requests that do not make a problem comprehensible.

I will now close this report. You are welcome to create a new issue as long as you provide reasonable information.

**Closed by Bizarrus** 2023-12-19 16:49 UTC
